class GuiEvents:
    VOICEVOX_TEST = "voicevox_test"
    GTTS_TEST = "gtts_test"
    GOOGLE_CLOUD_TTS_TEST = "google_cloud_tts_test"
    PYTTSX3_TEST = "pyttsx3_test"
    YOUTUBE_PSEUD_STT_TEST = "youtube_pseud_stt_test"
    GOOGLE_STREAMING_STT_TEST = "google_streaming_stt_test"
    SR_GOOGLE_STT_TEST = "sr_google_stt_test"
    STDIN_PSEUD_STT_TEST = "stdin_pseud_stt_test"
    WHISPER_API_STT_TEST = "whisper_api_stt_test"
    OBS_TEST = "obs_test"
    PARLAI_TEST = "parlai_test"
